version: '3.3'


services:
  mariadb:
    image: mariadb
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    container_name: mariadb
    restart: always
    env_file:
      - env.env
    volumes:
      - db_data:/home/tkempf-e/data
    ports: 
      - 3306:3306
    networks:
      - network
  nginx: 
    image: nginx
    depends_on: 
      - wordpress
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    container_name: nginx
    restart: always
    ports:
      - 443:443
    volumes:
      - app:/var/www/html/wordpress
    networks:
      - network

  wordpress:
    image: wordpress
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    depends_on: 
      - mariadb
    restart: always
    container_name: wordpress
    env_file:
      - env.env
    volumes:
      - app:/var/www/html/wordpress
    ports: 
      - 9000:9000
    networks:
      - network

volumes:
  db_data: 
    driver: local
    driver_opts:
      type: none
      device: /home/tkempf-e/data/data
      o: bind
  app: 
    driver: local
    driver_opts:
      type: none
      device: /home/tkempf-e/data/app
      o: bind

networks:
  network:
    driver: bridge 
